name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GabrielAlderige
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate snake"
          add: "dist/github-contribution-grid-snake.svg"
