name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: GabrielAlderige
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Gabriel Alderige
          author_email: galbyoficial@gmail.com
          message: atualizando snake 🐍
          add: 'dist/*.svg'
